### PR TITLE
Change with_stdin to &mut to fix #22

### LINKED ISSUE #22: `with_stdin` will take the ownership of command
The `with_stdin` will take the ownership of command. Therefore you cannot write chained functions like this:

```
Command::new("cat")
    .arg("-A")
    .with_stdin("42")
    .assert()
    .success();
```

Error:
```
error[E0507]: cannot move out of borrowed content
  --> /xxx.rs:43:5
   |
43 | /     Command::new("cat")
44 | |         .arg("-A")
   | |__________________^ cannot move out of borrowed content
```

### PR DESCRIPTION
**Pull request by mssun**
This is a quick fix. I didn't carefully read the code. Please review before merge. Thanks.

### CODE REVIEW

File: src/stdin.rs [hunk 1]
```diff
@@ -24,13 +24,13 @@ pub trait CommandStdInExt {
     ///     .with_stdin("42")
```
Comment (epage) [inline src/stdin.rs]: Could you modify this example so we have verification for your use case?

**Comment by epage** [comment]
Eh, CI is close enough
